version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    restart: on-failure
    ports:
      - 3000:3000
    platform: linux/x86_64
    depends_on:
      - backend
  
  backend:
    container_name: app_backend
    build: ./backend
    restart: 'always'
    ports:
      - 3001:3001
    platform: linux/x86_64
    environment:
      - APP_PORT=3001
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: postgres_db
    platform: linux/x86_64
    ports:
      - 3002:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    restart: 'always'
